//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Definux.Emeraude.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Definux.Emeraude.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMED_EMAIL_SUCCESS_MESSAGE.
        /// </summary>
        public static string ConfirmedEmailSuccecssMessage {
            get {
                return ResourceManager.GetString("ConfirmedEmailSuccecssMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMED_PASSWORD_DOES_NOT_MATCH_THE_PASSWORD.
        /// </summary>
        public static string ConfirmedPasswordDoesNotMatchThePassword {
            get {
                return ResourceManager.GetString("ConfirmedPasswordDoesNotMatchThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT_PASSWORD_IS_A_REQUIRED_FIELD.
        /// </summary>
        public static string CurrentPasswordIsARequiredField {
            get {
                return ResourceManager.GetString("CurrentPasswordIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_IS_A_REQUIRED_FIELD.
        /// </summary>
        public static string EmailIsARequiredField {
            get {
                return ResourceManager.GetString("EmailIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTERED_EMAIL_IS_IN_THE_WRONG_FORMAT.
        /// </summary>
        public static string EnteredEmailIsInTheWrongFormat {
            get {
                return ResourceManager.GetString("EnteredEmailIsInTheWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT_PASSWORD_MESSAGE.
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME_IS_A_REQUIRED_FIELD.
        /// </summary>
        public static string NameIsARequiedField {
            get {
                return ResourceManager.GetString("NameIsARequiedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW_PASSWORD_IS_A_REQUIRED_FIELD.
        /// </summary>
        public static string NewPasswordIsARequiredField {
            get {
                return ResourceManager.GetString("NewPasswordIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_HAVE_TO_CONTAINS_AT_LEAST_1_DIGIT.
        /// </summary>
        public static string PasswordHaveToContainsAtLeast1Digit {
            get {
                return ResourceManager.GetString("PasswordHaveToContainsAtLeast1Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_HAVE_TO_CONTAINS_AT_LEAST_1_LETTER.
        /// </summary>
        public static string PasswordHaveToContainsAtLeast1Letter {
            get {
                return ResourceManager.GetString("PasswordHaveToContainsAtLeast1Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_IS_A_REQUIRED_FIELD.
        /// </summary>
        public static string PasswordIsARequiredField {
            get {
                return ResourceManager.GetString("PasswordIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_MUST_BE_AT_LEAST_{0}_SYMBOLS.
        /// </summary>
        public static string PasswordMustBeAtLeastSymbols {
            get {
                return ResourceManager.GetString("PasswordMustBeAtLeastSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRESH_TOKEN_IS_A_REQUIRED_FIELD.
        /// </summary>
        public static string RefreshTokenIsRequiredField {
            get {
                return ResourceManager.GetString("RefreshTokenIsRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION_SUCCESS_MESSAGE.
        /// </summary>
        public static string RegistrationSuccessMessage {
            get {
                return ResourceManager.GetString("RegistrationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_CANNOT_BE_REGISTERED.
        /// </summary>
        public static string UserCannotBeRegistered {
            get {
                return ResourceManager.GetString("UserCannotBeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_EMAIL_OR_PASSWORD_IS_INCORRECT.
        /// </summary>
        public static string YourEmailOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("YourEmailOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_LOGIN_ATTEMPT_HAS_FAILED.
        /// </summary>
        public static string YourLoginAttemptHasFailed {
            get {
                return ResourceManager.GetString("YourLoginAttemptHasFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_PASSWORD_CANNOT_BE_RESET.
        /// </summary>
        public static string YourPasswordCannotBeReset {
            get {
                return ResourceManager.GetString("YourPasswordCannotBeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_PROFILE_EMAIL_IS_NOT_CONFIRMED.
        /// </summary>
        public static string YourProfileEmailIsNotConfirmed {
            get {
                return ResourceManager.GetString("YourProfileEmailIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_PROFILE_IS_TEMPORARY_LOCKED_OUT.
        /// </summary>
        public static string YourProfileIsTemporaryLockedOut {
            get {
                return ResourceManager.GetString("YourProfileIsTemporaryLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_REQUEST_CANNOT_BE_EXECUTED.
        /// </summary>
        public static string YourRequestCannotBeExecuted {
            get {
                return ResourceManager.GetString("YourRequestCannotBeExecuted", resourceCulture);
            }
        }
    }
}
