// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

const Home = () => import('../pages/home/Home');

const languageRoutePrefix = '';

export const routes = [
    { name: 'Home', path: `${languageRoutePrefix}/`, component: Home },
];
