namespace Definux.Emeraude.Admin.ClientBuilder.Shared
{
    public static class ClientBuilderConstants
    {
        public static string AutoGeneratedHeaderText = @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------";

        
    }
}
