namespace Emeraude.Application.ClientBuilder.Shared
{
    /// <summary>
    /// Constants used from the client builder.
    /// </summary>
    public static class ClientBuilderConstants
    {
        /// <summary>
        /// Header text which must be places at the beginning of each locked generated file.
        /// </summary>
        public const string AutoGeneratedHeaderText = @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------";

        /// <summary>
        /// Client Builder CORS policy name;
        /// </summary>
        public const string CorsPolicyName = "_ClientBuilderPolicy";

        /// <summary>
        /// Array of all origins of Client Builder web client.
        /// </summary>
        public static readonly string[] WebClientOrigins =
        {
            "http://localhost:3000",
            "https://cb.emeraude.dev",
        };
    }
}
