// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

// SomeConstants
export const PROJECT_NAME = 'EmDoggo';
export const PROJECT_CREATION_YEAR = 2020;

// ConstantsExposedByTheApplication
export const SOME_KEY1 = 'SomeValue1';
export const SOME_KEY2 = 'SomeValue2';

