// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

/**
 * @typedef CreatedResult
 * @property {string} createdEntityId
 */
/**
 * @typedef AddDogCommand
 * @property {string} name
 * @property {number} type
 * @property {number} breed
 * @property {string} nullableGuid
 * @property {string} nullableTimeSpan
 */
/**
 * @typedef SimpleResult
 * @property {boolean} successed
 */
/**
 * @typedef ComplexRequestResult
 * @property {boolean} success
 * @property {PaginatedList} paginatedCollection
 */
/**
 * @typedef PaginatedList
 * @property {Array<SomeResultItem>} items
 * @property {number} allItemsCount
 * @property {number} itemsCount
 * @property {number} pagesCount
 * @property {number} pageSize
 * @property {number} currentPage
 * @property {number} startRow
 */
/**
 * @typedef SomeResultItem
 * @property {string} id
 * @property {string} name
 */
/**
 * @typedef ComplexRequestCommand
 * @property {string} description
 * @property {Array<NestedComplexType>} nestedCollection
 */
/**
 * @typedef NestedComplexType
 * @property {string} id
 * @property {Array<DeepNestedComplexType>} deepCollection
 */
/**
 * @typedef DeepNestedComplexType
 * @property {string} name
 * @property {number} complexEnum
 */
/**
 * @typedef EnumValueItem
 * @property {string} name
 * @property {number} value
 * @property {string} key
 */
/**
 * @typedef LogFrontEndErrorCommand
 * @property {string} stackTrace
 * @property {string} source
 * @property {string} method
 * @property {string} message
 */
/**
 * @typedef UserAvatarTypeResult
 * @property {boolean} isDefault
 */
/**
 * @typedef ChangeUserAvatarCommand
 * @property {string} avatarFileBase64
 * @property {string} userId
 */
/**
 * @typedef ChangePasswordCommand
 * @property {string} userId
 * @property {string} currentPassword
 * @property {string} newPassword
 * @property {string} confirmedPassword
 */
/**
 * @typedef ChangeUserNameCommand
 * @property {string} userId
 * @property {string} newName
 */

export class DogsServiceAgent {

    /**
     * DogsApiController/AddDog
     * @param {AddDogCommand} request
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    addDog(request, queryParams = null, headers = null) { 
        let url = new URL(`/api/dogs/add`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'POST',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            body: JSON.stringify(request),
            credentials: 'include'
        })
            .then(response => response.json());
    }
}

export class EmptyServiceAgent {

    /**
     * EmptyApiController/ExampleAction
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    exampleAction(queryParams = null, headers = null) { 
        let url = new URL(`/api/empty/example`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'GET',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            credentials: 'include'
        })
            .then(response => response.json());
    }

    /**
     * EmptyApiController/ComplexRequestTypeAction
     * @param {ComplexRequestCommand} request
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    complexRequestTypeAction(request, queryParams = null, headers = null) { 
        let url = new URL(`/api/empty/complex`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'GET',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            credentials: 'include'
        })
            .then(response => response.json());
    }
}

export class EnumsServiceAgent {

    /**
     * EnumsApiController/GetEnumValueList
     * @param {string} enumTypeName
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    getEnumValueList(enumTypeName, queryParams = null, headers = null) { 
        let url = new URL(`/api/enums/${enumTypeName}`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'GET',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            credentials: 'include'
        })
            .then(response => response.json());
    }

    /**
     * EnumsApiController/GetEnumValue
     * @param {string} enumTypeName
     * @param {number} value
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    getEnumValue(enumTypeName, value, queryParams = null, headers = null) { 
        let url = new URL(`/api/enums/${enumTypeName}/${value}`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'GET',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            credentials: 'include'
        })
            .then(response => response.json());
    }
}

export class LoggerServiceAgent {

    /**
     * LoggerApiController/LogClientError
     * @param {LogFrontEndErrorCommand} request
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    logClientError(request, queryParams = null, headers = null) { 
        let url = new URL(`/api/logger/error`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'POST',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            body: JSON.stringify(request),
            credentials: 'include'
        })
            .then(response => response.json());
    }
}

export class UsersServiceAgent {

    /**
     * UsersApiController/GetUserAvatarType
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    getUserAvatarType(queryParams = null, headers = null) { 
        let url = new URL(`/api/users/current/avatar/type`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'GET',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            credentials: 'include'
        })
            .then(response => response.json());
    }

    /**
     * UsersApiController/ChangeUserAvatar
     * @param {ChangeUserAvatarCommand} request
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    changeUserAvatar(request, queryParams = null, headers = null) { 
        let url = new URL(`/api/users/current/avatar/change`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'POST',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            body: JSON.stringify(request),
            credentials: 'include'
        })
            .then(response => response.json());
    }

    /**
     * UsersApiController/ChangeUserPassword
     * @param {ChangePasswordCommand} request
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    changeUserPassword(request, queryParams = null, headers = null) { 
        let url = new URL(`/api/users/current/password/change`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'PUT',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            body: JSON.stringify(request),
            credentials: 'include'
        })
            .then(response => response.json());
    }

    /**
     * UsersApiController/ChangeUserName
     * @param {ChangeUserNameCommand} request
     * @param {Object} queryParams
     * @param {Object} headers
     * @returns {Promise}
     */
    changeUserName(request, queryParams = null, headers = null) { 
        let url = new URL(`/api/users/current/name/change`, window.location.origin);
        if (queryParams != null) {
            url.search = new URLSearchParams(queryParams).toString();
        }
        return fetch(url, {
            method: 'PUT',
            headers: headers || { 'Content-Type': 'application/json', 'Accept': 'application/json' },
            body: JSON.stringify(request),
            credentials: 'include'
        })
            .then(response => response.json());
    }
}

/**
 * @type {DogsServiceAgent}
 */
export const dogsServiceAgent = new DogsServiceAgent();

/**
 * @type {EmptyServiceAgent}
 */
export const emptyServiceAgent = new EmptyServiceAgent();

/**
 * @type {EnumsServiceAgent}
 */
export const enumsServiceAgent = new EnumsServiceAgent();

/**
 * @type {LoggerServiceAgent}
 */
export const loggerServiceAgent = new LoggerServiceAgent();

/**
 * @type {UsersServiceAgent}
 */
export const usersServiceAgent = new UsersServiceAgent();
