// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

const HomePage = () => import('../pages/Home/index.vue');
const DogsPage = () => import('../pages/Dogs/index.vue');
const ShopsPage = () => import('../pages/Shops/index.vue');

const languageRoutePrefix = '/:lang(bg)?';

export const routes = [
    { name: 'Home', path: `${languageRoutePrefix}/`, component: HomePage },
    { name: 'Dogs', path: `${languageRoutePrefix}/dogs`, component: DogsPage },
    { name: 'Shops', path: `${languageRoutePrefix}/shops`, component: ShopsPage },
];
