<template>
<div id="static-content-home-page">
<div v-if="languageId === 1">
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Authentication</h5>
        <p class="card-text">All authentication features like login, register, forgot password, reset password, confirm email and logout are provided.</p>
        <a href="/login" class="btn btn-primary">Log In</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">The auto CRUD and admin panel.</h5>
        <p class="card-text">Administration comes out of the box and all features comes by inheritance the Emeraude classes.</p>
        <a href="/admin" class="btn btn-primary">Go To Administration</a>
      </div>
    </div>
  </div>
</div>
</div>
<div v-if="languageId === 2">
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Управление на профилите</h5>
        <p class="card-text">Всички функционалности като вход, регистрация, забравена парола, промяна на парола, потвърждаване на имейл и изход от профил са предоставени.</p>
        <a href="/login" class="btn btn-primary">Влез В Профила</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Автоматичен CRUD и админ панел.</h5>
        <p class="card-text">Администрацията идва автоматично, като основните и функционалности идват чрез наследяване на класовете на Emeraude.</p>
        <a href="/admin" class="btn btn-primary">Отиди В Администрацията</a>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</template>

<script>
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
    export default {
        name: "HomePageStaticContent",
        props: {
            languageId: {
                type: Number,
                default: 1
            }
        }
    }
</script>