// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class AddDogCommandBindable : BindableBase
	{
		private string name;
		private DogTypeEnum type;
		private DogBreedEnum breed;
		private Guid? nullableGuid;
		private TimeSpan? nullableTimeSpan;
		private PaginatedListBindable paginatedDogs;

		public string Name 
		{ 
			get
			{
				return this.name;
			}
			set
			{
				SetProperty(ref this.name, value); 
			}
		}

		public DogTypeEnum Type 
		{ 
			get
			{
				return this.type;
			}
			set
			{
				SetProperty(ref this.type, value); 
			}
		}

		public DogBreedEnum Breed 
		{ 
			get
			{
				return this.breed;
			}
			set
			{
				SetProperty(ref this.breed, value); 
			}
		}

		public Guid? NullableGuid 
		{ 
			get
			{
				return this.nullableGuid;
			}
			set
			{
				SetProperty(ref this.nullableGuid, value); 
			}
		}

		public TimeSpan? NullableTimeSpan 
		{ 
			get
			{
				return this.nullableTimeSpan;
			}
			set
			{
				SetProperty(ref this.nullableTimeSpan, value); 
			}
		}

		public PaginatedListBindable PaginatedDogs 
		{ 
			get
			{
				return this.paginatedDogs;
			}
			set
			{
				SetProperty(ref this.paginatedDogs, value); 
			}
		}
	}
}
