// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class DeepNestedComplexTypeBindable : BindableBase
	{
		private string name;
		private ComplexEnumEnum complexEnum;

		public string Name 
		{ 
			get
			{
				return this.name;
			}
			set
			{
				SetProperty(ref this.name, value); 
			}
		}

		public ComplexEnumEnum ComplexEnum 
		{ 
			get
			{
				return this.complexEnum;
			}
			set
			{
				SetProperty(ref this.complexEnum, value); 
			}
		}
	}
}
