// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public enum DogTypeEnum
	{
		Hypoallergenic = 1,
		Fluffy = 2,
		BestFamily = 3,
		Smartest = 4,
		BestGuard = 5,
		KidFriendly = 6,
		BestWatch = 7,
		EasyToTrain = 8,
		LowShedding = 9,
	}

	public enum DogBreedEnum
	{
		GermanSpitz = 0,
		GermanShepherd = 1,
		Bulldog = 2,
		Poodle = 3,
		LabradorRetriever = 4,
		GoldenRetriever = 5,
		Beagle = 6,
		YorkshireTerrier = 7,
		Dachshund = 8,
		Chihuahua = 9,
		Pug = 10,
		FrenchBulldog = 11,
		SiberianHusky = 12,
		Boxer = 13,
		AustralianShepherd = 14,
		Greyhound = 15,
		Rottweiler = 16,
		Pomeranian = 17,
		Dobermann = 18,
		ShibaInu = 19,
		Dalmatian = 20,
		Samoyed = 21,
	}

	public enum ComplexEnumEnum
	{
		Complex1 = 1,
		Complex2 = 2,
		Complex3 = 3,
	}

}
