// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class MutationResultBindable : BindableBase
	{
		private string mutatedEntityId;
		private bool succeeded;

		public string MutatedEntityId 
		{ 
			get
			{
				return this.mutatedEntityId;
			}
			set
			{
				SetProperty(ref this.mutatedEntityId, value); 
			}
		}

		public bool Succeeded 
		{ 
			get
			{
				return this.succeeded;
			}
			set
			{
				SetProperty(ref this.succeeded, value); 
			}
		}
	}
}
