//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Definux.Emeraude.Presentation.PlatformBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Definux.Emeraude.Presentation.PlatformBase.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link for reset password has been sent to you.
        /// </summary>
        internal static string ALinkForResetPasswordHasBeenSentToYou {
            get {
                return ResourceManager.GetString("ALinkForResetPasswordHasBeenSentToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address confirmation has been failed.
        /// </summary>
        internal static string ChangeEmailAddressConfirmationHasBeenFailed {
            get {
                return ResourceManager.GetString("ChangeEmailAddressConfirmationHasBeenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address confirmation has been successful.
        /// </summary>
        internal static string ChangeEmailAddressConfirmationHasBeenSuccessful {
            get {
                return ResourceManager.GetString("ChangeEmailAddressConfirmationHasBeenSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email confirmation failed.
        /// </summary>
        internal static string ChangeEmailConfirmationFailed {
            get {
                return ResourceManager.GetString("ChangeEmailConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address confirmation has been failed.
        /// </summary>
        internal static string EmailAddressConfirmationHasBeenFailed {
            get {
                return ResourceManager.GetString("EmailAddressConfirmationHasBeenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address confirmation has been successful.
        /// </summary>
        internal static string EmailAddressConfirmationHasBeenSuccessful {
            get {
                return ResourceManager.GetString("EmailAddressConfirmationHasBeenSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation failed.
        /// </summary>
        internal static string EmailConfirmationFailed {
            get {
                return ResourceManager.GetString("EmailConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email address to complete the registration.
        /// </summary>
        internal static string PleaseConfirmYourEmailAddressToCompleteTheRegistration {
            get {
                return ResourceManager.GetString("PleaseConfirmYourEmailAddressToCompleteTheRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been successful.
        /// </summary>
        internal static string RegistrationHasBeenSuccessful {
            get {
                return ResourceManager.GetString("RegistrationHasBeenSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password successful.
        /// </summary>
        internal static string ResetPasswordSuccessful {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful change email confirmation.
        /// </summary>
        internal static string SuccessfulChangeEmailConfirmation {
            get {
                return ResourceManager.GetString("SuccessfulChangeEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful email confirmation.
        /// </summary>
        internal static string SuccessfulEmailConfirmation {
            get {
                return ResourceManager.GetString("SuccessfulEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful reset password request has been made.
        /// </summary>
        internal static string SuccessfulResetPasswordRequestHasBeenMade {
            get {
                return ResourceManager.GetString("SuccessfulResetPasswordRequestHasBeenMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address or password is incorrect..
        /// </summary>
        internal static string TheEmailAddressOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("TheEmailAddressOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot be registered.
        /// </summary>
        internal static string UserCannotBeRegistered {
            get {
                return ResourceManager.GetString("UserCannotBeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt has failed.
        /// </summary>
        internal static string YourLoginAttemptHasFailed {
            get {
                return ResourceManager.GetString("YourLoginAttemptHasFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot be reset.
        /// </summary>
        internal static string YourPasswordCannotBeReset {
            get {
                return ResourceManager.GetString("YourPasswordCannotBeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        internal static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is temporary locked out.
        /// </summary>
        internal static string YourProfileIsTemporaryLockedOut {
            get {
                return ResourceManager.GetString("YourProfileIsTemporaryLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request cannot be executed.
        /// </summary>
        internal static string YourRequestCannotBeExecuted {
            get {
                return ResourceManager.GetString("YourRequestCannotBeExecuted", resourceCulture);
            }
        }
    }
}
