// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Definux.Emeraude.AutoGenerated.TranslationKeys
{
    public static class EmeraudeTranslationKeys
    {
        public const string Login = "LOGIN";
        public const string Email = "EMAIL";
        public const string Password = "PASSWORD";
        public const string ForgotPassword = "FORGOT_PASSWORD";
        public const string DontHaveAProfile = "DONT_HAVE_A_PROFILE";
        public const string FullName = "FULL_NAME";
        public const string ConfirmPassword = "CONFIRM_PASSWORD";
        public const string RegisterTitle = "REGISTER_TITLE";
        public const string AlreadyHaveAProfile = "ALREADY_HAVE_A_PROFILE";
        public const string YourRegistrationHasBeenSuccessfullyCompleted = "YOUR_REGISTRATION_HAS_BEEN_SUCCESSFULLY_COMPLETED";
        public const string CheckYourEmailForConfirmationLink = "CHECK_YOUR_EMAIL_FOR_CONFIRMATION_LINK";
        public const string SwitchTo = "SWITCH_TO";
        public const string English = "ENGLISH";
        public const string Bulgarian = "BULGARIAN";
        public const string Home = "HOME";
        public const string Dogs = "DOGS";
        public const string Shops = "SHOPS";
        public const string Logout = "LOGOUT";
        public const string Offers = "OFFERS";
        public const string DogTypeHypoallergenic = "DOG_TYPE_HYPOALLERGENIC";
        public const string DogBreedGermanSpitz = "DOG_BREED_GERMAN_SPITZ";
        public const string DogBreedGermanShepherd = "DOG_BREED_GERMAN_SHEPHERD";
        public const string DogBreedBulldog = "DOG_BREED_BULLDOG";
        public const string DogBreedPoodle = "DOG_BREED_POODLE";
        public const string DogBreedLabradorRetriever = "DOG_BREED_LABRADOR_RETRIEVER";
        public const string DogBreedGoldenRetriever = "DOG_BREED_GOLDEN_RETRIEVER";
        public const string DogBreedBeagle = "DOG_BREED_BEAGLE";
        public const string DogBreedYorkshireTerrier = "DOG_BREED_YORKSHIRE_TERRIER";
        public const string DogBreedDachshund = "DOG_BREED_DACHSHUND";
        public const string DogBreedChihuahua = "DOG_BREED_CHIHUAHUA";
        public const string DogBreedPug = "DOG_BREED_PUG";
        public const string DogBreedFrenchBulldog = "DOG_BREED_FRENCH_BULLDOG";
        public const string DogBreedSiberianHusky = "DOG_BREED_SIBERIAN_HUSKY";
        public const string DogBreedBoxer = "DOG_BREED_BOXER";
        public const string DogBreedAustralianShepherd = "DOG_BREED_AUSTRALIAN_SHEPHERD";
        public const string DogBreedGreyhound = "DOG_BREED_GREYHOUND";
        public const string DogBreedRottweiler = "DOG_BREED_ROTTWEILER";
        public const string DogBreedPomeranian = "DOG_BREED_POMERANIAN";
        public const string DogBreedDalmatian = "DOG_BREED_DALMATIAN";
        public const string DogBreedShibaInu = "DOG_BREED_SHIBA_INU";
        public const string DogBreedSamoyed = "DOG_BREED_SAMOYED";
        public const string DogBreedDobermann = "DOG_BREED_DOBERMANN";
        public const string DogType = "DOG_TYPE";
        public const string DogBreed = "DOG_BREED";
        public const string Name = "NAME";
        public const string Add = "ADD";
        public const string DogTypeFluffy = "DOG_TYPE_FLUFFY";
        public const string DogTypeBestFamily = "DOG_TYPE_BEST_FAMILY";
        public const string DogTypeSmartest = "DOG_TYPE_SMARTEST";
        public const string DogTypeBestGuard = "DOG_TYPE_BEST_GUARD";
        public const string DogTypeKidFriendly = "DOG_TYPE_KID_FRIENDLY";
        public const string DogTypeBestWatch = "DOG_TYPE_BEST_WATCH";
        public const string DogTypeEasyToTrain = "DOG_TYPE_EASY_TO_TRAIN";
        public const string DogTypeLowShedding = "DOG_TYPE_LOW_SHEDDING";
        public const string LoginTitle = "LOGIN_TITLE";
        public const string LoginSubmit = "LOGIN_SUBMIT";
        public const string ForgotPasswordTitle = "FORGOT_PASSWORD_TITLE";
        public const string IRememberedMyPassword = "I_REMEMBERED_MY_PASSWORD";
        public const string ForgotPasswordSubmit = "FORGOT_PASSWORD_SUBMIT";
        public const string ConfirmedPassword = "CONFIRMED_PASSWORD";
        public const string RegisterSubmit = "REGISTER_SUBMIT";
        public const string YourEmailOrPasswordIsIncorrect = "YOUR_EMAIL_OR_PASSWORD_IS_INCORRECT";
        public const string PasswordIsARequiredField = "PASSWORD_IS_A_REQUIRED_FIELD";
        public const string EmailIsARequiredField = "EMAIL_IS_A_REQUIRED_FIELD";
    }
}
