// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

const Home = () => import('../pages/home/Home');
const Dogs = () => import('../pages/dogs/Dogs');
const Shops = () => import('../pages/shops/Shops');

const languageRoutePrefix = '/:lang(bg)?';

export const routes = [
    { name: 'Home', path: `${languageRoutePrefix}/`, component: Home },
    { name: 'Dogs', path: `${languageRoutePrefix}/dogs`, component: Dogs },
    { name: 'Shops', path: `${languageRoutePrefix}/shops`, component: Shops },
];
