//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Definux.Emeraude.Application.Identity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Definux.Emeraude.Application.Identity.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed password does not match the password.
        /// </summary>
        internal static string ConfirmedPasswordDoesNotMatchThePassword {
            get {
                return ResourceManager.GetString("ConfirmedPasswordDoesNotMatchThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required.
        /// </summary>
        internal static string CurrentPasswordIsRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is in an invalid format.
        /// </summary>
        internal static string EmailAddressIsInAnInvalidFormat {
            get {
                return ResourceManager.GetString("EmailAddressIsInAnInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        internal static string EmailAddressIsRequired {
            get {
                return ResourceManager.GetString("EmailAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login provider is required.
        /// </summary>
        internal static string ExternalLoginProviderIsRequired {
            get {
                return ResourceManager.GetString("ExternalLoginProviderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains at least {0} characters.
        /// </summary>
        internal static string PasswordMustContainsAtLeastNCharacters {
            get {
                return ResourceManager.GetString("PasswordMustContainsAtLeastNCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains at least {0} unique characters.
        /// </summary>
        internal static string PasswordMustContainsAtLeastNUniqueCharacters {
            get {
                return ResourceManager.GetString("PasswordMustContainsAtLeastNUniqueCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains at least one digit.
        /// </summary>
        internal static string PasswordMustContainsAtLeastOneDigit {
            get {
                return ResourceManager.GetString("PasswordMustContainsAtLeastOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains at least one letter.
        /// </summary>
        internal static string PasswordMustContainsAtLeastOneLetter {
            get {
                return ResourceManager.GetString("PasswordMustContainsAtLeastOneLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains at least one lower case letter.
        /// </summary>
        internal static string PasswordMustContainsAtLeastOneLowerCaseLetter {
            get {
                return ResourceManager.GetString("PasswordMustContainsAtLeastOneLowerCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains at least one non-alphanumeric symbol.
        /// </summary>
        internal static string PasswordMustContainsAtLeastOneNonAlphanumericSymbol {
            get {
                return ResourceManager.GetString("PasswordMustContainsAtLeastOneNonAlphanumericSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains at least one upper case letter.
        /// </summary>
        internal static string PasswordMustContainsAtLeastOneUpperCaseLetter {
            get {
                return ResourceManager.GetString("PasswordMustContainsAtLeastOneUpperCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required.
        /// </summary>
        internal static string RefreshTokenIsRequired {
            get {
                return ResourceManager.GetString("RefreshTokenIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot be registered.
        /// </summary>
        internal static string UserCannotBeRegistered {
            get {
                return ResourceManager.GetString("UserCannotBeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with that email address exists.
        /// </summary>
        internal static string UserWithThatEmailAddressExists {
            get {
                return ResourceManager.GetString("UserWithThatEmailAddressExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile email address is not confirmed.
        /// </summary>
        internal static string YourProfileEmailAddressIsNotConfirmed {
            get {
                return ResourceManager.GetString("YourProfileEmailAddressIsNotConfirmed", resourceCulture);
            }
        }
    }
}
