// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

export const DogType = {
	Hypoallergenic: 1,
	Fluffy: 2,
	BestFamily: 3,
	Smartest: 4,
	BestGuard: 5,
	KidFriendly: 6,
	BestWatch: 7,
	EasyToTrain: 8,
	LowShedding: 9,
};

export const DogTypeValueItems = [
  {
    "name": "Hypoallergenic",
    "value": 1,
    "key": "DOG_TYPE_HYPOALLERGENIC"
  },
  {
    "name": "Fluffy",
    "value": 2,
    "key": "DOG_TYPE_FLUFFY"
  },
  {
    "name": "BestFamily",
    "value": 3,
    "key": "DOG_TYPE_BEST_FAMILY"
  },
  {
    "name": "Smartest",
    "value": 4,
    "key": "DOG_TYPE_SMARTEST"
  },
  {
    "name": "BestGuard",
    "value": 5,
    "key": "DOG_TYPE_BEST_GUARD"
  },
  {
    "name": "KidFriendly",
    "value": 6,
    "key": "DOG_TYPE_KID_FRIENDLY"
  },
  {
    "name": "BestWatch",
    "value": 7,
    "key": "DOG_TYPE_BEST_WATCH"
  },
  {
    "name": "EasyToTrain",
    "value": 8,
    "key": "DOG_TYPE_EASY_TO_TRAIN"
  },
  {
    "name": "LowShedding",
    "value": 9,
    "key": "DOG_TYPE_LOW_SHEDDING"
  }
];

export const DogBreed = {
	GermanSpitz: 0,
	GermanShepherd: 1,
	Bulldog: 2,
	Poodle: 3,
	LabradorRetriever: 4,
	GoldenRetriever: 5,
	Beagle: 6,
	YorkshireTerrier: 7,
	Dachshund: 8,
	Chihuahua: 9,
	Pug: 10,
	FrenchBulldog: 11,
	SiberianHusky: 12,
	Boxer: 13,
	AustralianShepherd: 14,
	Greyhound: 15,
	Rottweiler: 16,
	Pomeranian: 17,
	Dobermann: 18,
	ShibaInu: 19,
	Dalmatian: 20,
	Samoyed: 21,
};

export const DogBreedValueItems = [
  {
    "name": "GermanSpitz",
    "value": 0,
    "key": "DOG_BREED_GERMAN_SPITZ"
  },
  {
    "name": "GermanShepherd",
    "value": 1,
    "key": "DOG_BREED_GERMAN_SHEPHERD"
  },
  {
    "name": "Bulldog",
    "value": 2,
    "key": "DOG_BREED_BULLDOG"
  },
  {
    "name": "Poodle",
    "value": 3,
    "key": "DOG_BREED_POODLE"
  },
  {
    "name": "LabradorRetriever",
    "value": 4,
    "key": "DOG_BREED_LABRADOR_RETRIEVER"
  },
  {
    "name": "GoldenRetriever",
    "value": 5,
    "key": "DOG_BREED_GOLDEN_RETRIEVER"
  },
  {
    "name": "Beagle",
    "value": 6,
    "key": "DOG_BREED_BEAGLE"
  },
  {
    "name": "YorkshireTerrier",
    "value": 7,
    "key": "DOG_BREED_YORKSHIRE_TERRIER"
  },
  {
    "name": "Dachshund",
    "value": 8,
    "key": "DOG_BREED_DACHSHUND"
  },
  {
    "name": "Chihuahua",
    "value": 9,
    "key": "DOG_BREED_CHIHUAHUA"
  },
  {
    "name": "Pug",
    "value": 10,
    "key": "DOG_BREED_PUG"
  },
  {
    "name": "FrenchBulldog",
    "value": 11,
    "key": "DOG_BREED_FRENCH_BULLDOG"
  },
  {
    "name": "SiberianHusky",
    "value": 12,
    "key": "DOG_BREED_SIBERIAN_HUSKY"
  },
  {
    "name": "Boxer",
    "value": 13,
    "key": "DOG_BREED_BOXER"
  },
  {
    "name": "AustralianShepherd",
    "value": 14,
    "key": "DOG_BREED_AUSTRALIAN_SHEPHERD"
  },
  {
    "name": "Greyhound",
    "value": 15,
    "key": "DOG_BREED_GREYHOUND"
  },
  {
    "name": "Rottweiler",
    "value": 16,
    "key": "DOG_BREED_ROTTWEILER"
  },
  {
    "name": "Pomeranian",
    "value": 17,
    "key": "DOG_BREED_POMERANIAN"
  },
  {
    "name": "Dobermann",
    "value": 18,
    "key": "DOG_BREED_DOBERMANN"
  },
  {
    "name": "ShibaInu",
    "value": 19,
    "key": "DOG_BREED_SHIBA_INU"
  },
  {
    "name": "Dalmatian",
    "value": 20,
    "key": "DOG_BREED_DALMATIAN"
  },
  {
    "name": "Samoyed",
    "value": 21,
    "key": "DOG_BREED_SAMOYED"
  }
];

export const ComplexEnum = {
	Complex1: 1,
	Complex2: 2,
	Complex3: 3,
};

export const ComplexEnumValueItems = [
  {
    "name": "Complex1",
    "value": 1,
    "key": "COMPLEX_ENUM_COMPLEX1"
  },
  {
    "name": "Complex2",
    "value": 2,
    "key": "COMPLEX_ENUM_COMPLEX2"
  },
  {
    "name": "Complex3",
    "value": 3,
    "key": "COMPLEX_ENUM_COMPLEX3"
  }
];

