//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emeraude.Cli.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emeraude.Cli.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLI configuration file has been found..
        /// </summary>
        internal static string CliFileFound {
            get {
                return ResourceManager.GetString("CliFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLI configuration file has not been found..
        /// </summary>
        internal static string CliFileNotFound {
            get {
                return ResourceManager.GetString("CliFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command has been created successfully..
        /// </summary>
        internal static string CommandSuccessfullyCreated {
            get {
                return ResourceManager.GetString("CommandSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the files already exist. Overriding is not possible for safety reasons..
        /// </summary>
        internal static string FileExistMessage {
            get {
                return ResourceManager.GetString("FileExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid usage of CLI command..
        /// </summary>
        internal static string InvalidCliCommandUsage {
            get {
                return ResourceManager.GetString("InvalidCliCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request name must ends with Query or Command - example: GetSomethingQuery or MakeSomethingCommand.
        /// </summary>
        internal static string InvalidRequestCommand {
            get {
                return ResourceManager.GetString("InvalidRequestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLI configuration file cannot be found. Be sure you execute the command in the &apos;em-cli.json&apos; directory..
        /// </summary>
        internal static string MissedCliConfigFile {
            get {
                return ResourceManager.GetString("MissedCliConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page has been created successfully..
        /// </summary>
        internal static string PageSuccessfullyCreated {
            get {
                return ResourceManager.GetString("PageSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project initialization requires project name parameter..
        /// </summary>
        internal static string ProjectRequiresAName {
            get {
                return ResourceManager.GetString("ProjectRequiresAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project structure has been successfully created..
        /// </summary>
        internal static string ProjectSuccessfullyCreated {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query has been created successfully..
        /// </summary>
        internal static string QuerySuccessfullyCreated {
            get {
                return ResourceManager.GetString("QuerySuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request cannot be created..
        /// </summary>
        internal static string RequestCannotBeCreated {
            get {
                return ResourceManager.GetString("RequestCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;em&apos; to check available commands..
        /// </summary>
        internal static string SeeHelpForCli {
            get {
                return ResourceManager.GetString("SeeHelpForCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something unexpected happened. :(.
        /// </summary>
        internal static string SomethingUnexpectedHappened {
            get {
                return ResourceManager.GetString("SomethingUnexpectedHappened", resourceCulture);
            }
        }
    }
}
