// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

import Vue from 'vue';
import en from './en.json';
import bg from './bg.json';

import VueI18n from 'vue-i18n';

Vue.use(VueI18n);

const messages = { 
    'en': en,
    'bg': bg,
};
const i18n = new VueI18n({
    locale: 'en',
    fallbackLocale: 'en',
    messages
});

export default i18n;
