// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Definux.Emeraude.AutoGenerated.DataTransferObjects;
using System;
using System.Collections.ObjectModel;
using System.Threading.Tasks;

namespace Definux.Emeraude.AutoGenerated.ServiceAgents
{
    public interface IDogsServiceAgent
    {
        Task<CreatedResultBindable> AddDogAsync(AddDogCommandBindable request);

    }
}