// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Definux.Emeraude.AutoGenerated.DataTransferObjects;
using System;
using System.Collections.ObjectModel;
using System.Threading.Tasks;

namespace Definux.Emeraude.AutoGenerated.ServiceAgents
{
    public interface IUsersServiceAgent
    {
        Task<UserAvatarTypeResultBindable> GetUserAvatarTypeAsync();

        Task<SimpleResultBindable> ChangeUserAvatarAsync(ChangeUserAvatarCommandBindable request);

        Task<SimpleResultBindable> ChangeUserPasswordAsync(ChangePasswordCommandBindable request);

        Task<SimpleResultBindable> ChangeUserNameAsync(ChangeUserNameCommandBindable request);

    }
}