// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Definux.Emeraude.AutoGenerated.DataTransferObjects;
using Definux.Emeraude.MobileSdk.Configuration;
using Definux.Emeraude.MobileSdk.ServiceAgents;
using Definux.Emeraude.MobileSdk.ServiceAgents.Http;
using System;
using System.Collections.ObjectModel;
using System.Threading.Tasks;

namespace Definux.Emeraude.AutoGenerated.ServiceAgents
{
    public class UsersServiceAgent : ServiceAgent, IUsersServiceAgent
    {
        public UsersServiceAgent(
            IEmConfiguration configuration,
            IHttpClientFactory clientFactory)
            : base(configuration, clientFactory)
        {
        }

        public async Task<UserAvatarTypeResultBindable> GetUserAvatarTypeAsync()
        {
	        return await GetAsync<UserAvatarTypeResultBindable>($"/api/users/current/avatar/type");
        }

        public async Task<SimpleResultBindable> ChangeUserAvatarAsync(ChangeUserAvatarCommandBindable request)
        {
	        return await PostAsync<ChangeUserAvatarCommandBindable, SimpleResultBindable>($"/api/users/current/avatar/change", request);
        }

        public async Task<SimpleResultBindable> ChangeUserPasswordAsync(ChangePasswordCommandBindable request)
        {
	        return await PutAsync<ChangePasswordCommandBindable, SimpleResultBindable>($"/api/users/current/password/change", request);
        }

        public async Task<SimpleResultBindable> ChangeUserNameAsync(ChangeUserNameCommandBindable request)
        {
	        return await PutAsync<ChangeUserNameCommandBindable, SimpleResultBindable>($"/api/users/current/name/change", request);
        }
    }
}