// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class ChangeUserAvatarCommandBindable : BindableBase
	{
		private string avatarFileBase64;
		private Guid? userId;

		public string AvatarFileBase64 
		{ 
			get
			{
				return this.avatarFileBase64;
			}
			set
			{
				SetProperty(ref this.avatarFileBase64, value); 
			}
		}

		public Guid? UserId 
		{ 
			get
			{
				return this.userId;
			}
			set
			{
				SetProperty(ref this.userId, value); 
			}
		}
	}
}
