// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class ChangeUserNameCommandBindable : BindableBase
	{
		private Guid? userId;
		private string newName;

		public Guid? UserId 
		{ 
			get
			{
				return this.userId;
			}
			set
			{
				SetProperty(ref this.userId, value); 
			}
		}

		public string NewName 
		{ 
			get
			{
				return this.newName;
			}
			set
			{
				SetProperty(ref this.newName, value); 
			}
		}
	}
}
