// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class ComplexRequestCommandBindable : BindableBase
	{
		private string description;
		private ObservableCollection<NestedComplexTypeBindable> nestedCollection;

		public string Description 
		{ 
			get
			{
				return this.description;
			}
			set
			{
				SetProperty(ref this.description, value); 
			}
		}

		public ObservableCollection<NestedComplexTypeBindable> NestedCollection 
		{ 
			get
			{
				return this.nestedCollection;
			}
			set
			{
				SetProperty(ref this.nestedCollection, value); 
			}
		}
	}
}
