// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class ComplexRequestResultBindable : BindableBase
	{
		private bool success;
		private PaginatedListBindable paginatedCollection;

		public bool Success 
		{ 
			get
			{
				return this.success;
			}
			set
			{
				SetProperty(ref this.success, value); 
			}
		}

		public PaginatedListBindable PaginatedCollection 
		{ 
			get
			{
				return this.paginatedCollection;
			}
			set
			{
				SetProperty(ref this.paginatedCollection, value); 
			}
		}
	}
}
