// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class EnumValueItemBindable : BindableBase
	{
		private string name;
		private int value;
		private string key;

		public string Name 
		{ 
			get
			{
				return this.name;
			}
			set
			{
				SetProperty(ref this.name, value); 
			}
		}

		public int Value 
		{ 
			get
			{
				return this.value;
			}
			set
			{
				SetProperty(ref this.value, value); 
			}
		}

		public string Key 
		{ 
			get
			{
				return this.key;
			}
			set
			{
				SetProperty(ref this.key, value); 
			}
		}
	}
}
