// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class PaginatedListBindable : BindableBase
	{
		private ObservableCollection<SomeResultItemBindable> items;
		private int allItemsCount;
		private int itemsCount;
		private int pagesCount;
		private int pageSize;
		private int currentPage;
		private int startRow;

		public ObservableCollection<SomeResultItemBindable> Items 
		{ 
			get
			{
				return this.items;
			}
			set
			{
				SetProperty(ref this.items, value); 
			}
		}

		public int AllItemsCount 
		{ 
			get
			{
				return this.allItemsCount;
			}
			set
			{
				SetProperty(ref this.allItemsCount, value); 
			}
		}

		public int ItemsCount 
		{ 
			get
			{
				return this.itemsCount;
			}
			set
			{
				SetProperty(ref this.itemsCount, value); 
			}
		}

		public int PagesCount 
		{ 
			get
			{
				return this.pagesCount;
			}
			set
			{
				SetProperty(ref this.pagesCount, value); 
			}
		}

		public int PageSize 
		{ 
			get
			{
				return this.pageSize;
			}
			set
			{
				SetProperty(ref this.pageSize, value); 
			}
		}

		public int CurrentPage 
		{ 
			get
			{
				return this.currentPage;
			}
			set
			{
				SetProperty(ref this.currentPage, value); 
			}
		}

		public int StartRow 
		{ 
			get
			{
				return this.startRow;
			}
			set
			{
				SetProperty(ref this.startRow, value); 
			}
		}
	}
}
