// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class SomeResultItemBindable : BindableBase
	{
		private Guid id;
		private string name;

		public Guid Id 
		{ 
			get
			{
				return this.id;
			}
			set
			{
				SetProperty(ref this.id, value); 
			}
		}

		public string Name 
		{ 
			get
			{
				return this.name;
			}
			set
			{
				SetProperty(ref this.name, value); 
			}
		}
	}
}
