// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using Prism.Mvvm;

namespace Definux.Emeraude.AutoGenerated.DataTransferObjects
{
	public class UserAvatarTypeResultBindable : BindableBase
	{
		private bool isDefault;

		public bool IsDefault 
		{ 
			get
			{
				return this.isDefault;
			}
			set
			{
				SetProperty(ref this.isDefault, value); 
			}
		}
	}
}
