// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Prism.Ioc;

namespace Definux.Emeraude.AutoGenerated.ServiceAgents
{
    public static class ContainerRegistryExtensions
    {
        public static IContainerRegistry RegisterEmeraudeAutoGeneratedServiceAgents(this IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterSingleton<IDogsServiceAgent, DogsServiceAgent>();
            containerRegistry.RegisterSingleton<IEmptyServiceAgent, EmptyServiceAgent>();

            return containerRegistry;
        }
    }
}