// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Emeraude Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Definux.Emeraude.AutoGenerated.DataTransferObjects;
using Definux.Emeraude.MobileSdk.Configuration;
using Definux.Emeraude.MobileSdk.ServiceAgents;
using Definux.Emeraude.MobileSdk.ServiceAgents.Http;
using System;
using System.Collections.ObjectModel;
using System.Threading.Tasks;

namespace Definux.Emeraude.AutoGenerated.ServiceAgents
{
    public class EmptyServiceAgent : ServiceAgent, IEmptyServiceAgent
    {
        public EmptyServiceAgent(
            IEmConfiguration configuration,
            IHttpClientFactory clientFactory)
            : base(configuration, clientFactory)
        {
        }

        public async Task<SimpleResultBindable> ExampleActionAsync()
        {
	        return await GetAsync<SimpleResultBindable>($"/api/empty/example");
        }

        public async Task<ComplexRequestResultBindable> ComplexRequestTypeActionAsync(ComplexRequestCommandBindable request)
        {
	        return await GetAsync<ComplexRequestResultBindable>($"/api/empty/complex");
        }
    }
}